### PR TITLE
Fix True/False identity checks

### PR DESCRIPTION
**Pull request by justvanrossum**
To do:

```python
    if value is True:  # or is False
        ...
```
...is unidiomatic and bad advice.

### CODE REVIEW

**Comment by roberto-arista** [comment]
I agree with your corrections, and that's the way I would probably write my code.

But I have the feeling that often beginners struggle to figure out that `value` is a boolean value at all. With `is True` that becomes a bit more easy to grasp. I'll accept your pull request, in the future I should adjust some variable names.

**Comment by roberto-arista** [comment]
Thanks for reviewing the code!

**Comment by justvanrossum** [comment]
It's not that `value` is necessarily a boolean, it's that in `if <something>`, the `<something>` is evaluated in a boolean context (most values have a truth value, whether they are actual boolean objects or not)

But even if `value` is a boolean, comparing a boolean to a boolean is a tautology.

Thanks for the quick merge! I'm using it my class now, so I found this from practical usage, not by means of nosy review :)

**Comment by roberto-arista** [comment]
> But even if value is a boolean, comparing a boolean to a boolean is a tautology.

Totally agree :)

Will be online soon

**Pull request merged**
